`? Still manual SQL file. Not migration but not executed. Hmm.

Maybe final can say "A tabela precisa ser criada via SQL no console; não consigo executar o SQL aqui". But user asked create. We can still implement front-end; incomplete. But guidelines "All edits ... directly built/rendered, NEVER partial". But DB not built. Need maybe rely on existing Supabase? There is no table. Need create.

Maybe there is a SQL tool hidden not listed due prompt? No. In previous tasks, ChatGPT can call `execute SQL` if available, but not here. We only have dyad tools. Could maybe use `<dyad-command type="rebuild">` not SQL. No.

Need maybe use Supabase client to create table using REST? PostgREST doesn't support CREATE TABLE. Supabase has Management API with project API key maybe not. Not possible.

Maybe use `supabaseAdmin.rpc('exec_sql', ...)` if custom function exists? No.
Maybe use Edge Function to use `pg` package? Deno can import `npm:pg`? But no DB_URL? Secrets include SUPABASE_DB_URL. Edge function could run SQL with `pg` from npm? That's not typical. Could create edge function `documentos-setup` that executes SQL via pg and then client calls it. But user didn't ask. But could implement DB creation in Edge Function with service role. However need install Deno npm module? Could import `npm:pg@8.13.1` in edge function? Supabase Edge Functions support npm specifiers? I think yes in new runtime? But not sure. Also this is overengineering.
Could create an Edge Function `documentos-setup` that uses `supabaseAdmin` and then `supabaseAdmin.from("documentos")`? no.
Could use Supabase Management API with service role? no.

Maybe use Supabase SQL through `supabaseAdmin.auth.admin`? no.

Let's see existing migrations were generated by external system, maybe can create new migration file but not manually. No.

Could maybe use `dyad-write` to update `src/integrations/supabase/types.ts` manually for documentos. Need do that. But if DB table not created, types don't matter. Need maybe update type.

Need maybe use `@supabase/supabase-js` storage. Need maybe create bucket. Without SQL, storage bucket may not exist. Could create bucket via Supabase JS? `supabase.storage.createBucket` is client method? Actually `supabase.storage.from(bucketId)` but no `createBucket` in js? There is `supabase.storage.createBucket(id, options)`? I think supabase-js StorageApi has createBucket, updateBucket, getBucket, listBuckets, emptyBucket, deleteBucket. Yes maybe. We can create bucket from client if user has permissions? Anon likely cannot create buckets. Admin client cannot create bucket? Could call `supabase.storage.createBucket("documentos", { public: false })` but RLS/storage policy? I think bucket creation uses REST admin endpoint maybe anon cannot. We can't.

Maybe bucket already exists? Not in schema. Need create. Could use Edge Function with service role to create bucket? Supabase JS admin client storage.createBucket maybe with service role key? Edge functions can create bucket. But table still.

Could create an Edge Function that creates table? no.

Could create an Edge Function `documentos-admin` that uses `supabaseAdmin` and perhaps `supabaseAdmin.from("documentos")` but table absent. no.

Could create table via `supabaseAdmin.rpc("documentos_create_schema")` if we create SQL function? no.

Maybe use `supabaseAdmin.from("documentos").select` no.

Could use Supabase "execute SQL" not available. Hmm.

Need maybe ask user for permission to run SQL? But they asked create. We can state "Preciso criar a tabela no banco; não tenho a ferramenta de SQL disponível neste chat. Posso preparar o SQL." But final? We need maybe not edit code until DB? But we can implement code.

Let's maybe include SQL in a `dyad-write` file named `src/lib/documentos-schema.sql`? But user won't know. Better not.

Maybe we can write a migration but not "manual"? Hmm.

Let's focus code. Need maybe update types. Need maybe add dependency.

Need be careful no markdown code blocks. Use dyad-write.

Need maybe check package uses React Router not TanStack. Fine.

Need maybe use `confirm()`? Guidelines prefer Dialog not confirm. For admin delete? Not needed. For upload, no confirm.

Need maybe use `alert`? no.

Need maybe use toast.

Need maybe use shadcn. Good.

Need maybe avoid try/catch? Guideline says don't catch errors with try/catch unless specifically requested. But existing code uses try/catch. For async user action, we can use try/catch? It says don't catch errors with try/catch unless specifically requested. Hmm. But we need show toast. Existing code catches. We can follow style. But maybe avoid catch? We need handle async errors. Could let errors bubble? But then no toast. Use try/catch. Existing style.

Need maybe create `src/lib/documentos.ts`. Need maybe use pdfjs and pdf-lib. Need import Blob? TS ok.

Potential TypeScript issues:
- `pdfjsLib.getDocument` type maybe overloaded. `pdfjsLib.GlobalWorkerOptions.workerSrc`.
- `pdfjsLib.getDocument({ data: arrayBuffer })` with ArrayBuffer. In v5, getDocument accepts string/TypedArray/ArrayBuffer. ok.
- `pdfjsLib.PDFPageProxy` etc.
- pdf-lib import: `import { PDFDocument } from "pdf-lib";`
- `createSinglePagePdf(file: File, pageNumber: number): Promise<Blob>`:
const originalPdf = await PDFDocument.load(await file.arrayBuffer());
const [page] = await newPdf.copyPages(originalPdf, [pageNumber - 1]);
newPdf.addPage(page);
const bytes = await newPdf.save();
return new Blob([bytes], { type: "application/pdf" });
Need maybe `PDFDocument.load(await file.arrayBuffer())` can accept ArrayBuffer. ok.
- `normalizeText`:
return (value ?? "")
.toLocaleLowerCase("pt-BR")
.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
.replace(/[^a-z0-9]+/g, " ")
.replace(/\s+/g, " ")
.trim();
- `levenshteinDistance`.
- `similarity(a,b)`:
if !a||!b return 0; if a.includes(b) || b.includes(a) return 1; const max = Math.max(a.length,b.length); return 1 - distance/max.
- `findBestProfileMatch(pageText, profiles)`:
const page = normalizeText(pageText);
let best = null;
for profile of profiles:
const profileName = normalizeText(profile.nome);
if (!profileName) continue;
let score = similarity(page, profileName);
const tokens = profileName.split(" ").filter(t=>t.length>2);
if (tokens.length >=2 && tokens.every(t => page.includes(t))) score = Math.max(score, 0.92);
if (page.includes(profileName)) score = 1;
if score > best.score...
return { profile, score, pageText: profile.nome }
- Maybe threshold 0.82. Good.
- `getDocStoragePath`.

Need update Supabase types:
Add Documentos table in public Tables:
Row: id, colaborador_id: string | null, tipo: "contracheque" | "folha_ponto"? But generated types use string maybe. We'll add type strings to avoid compile.
Insert/Update.
Enums? no.
Need maybe `Tables` type includes documentos.
Need maybe `Database["public"]["Enums"]` no new.
Need maybe update Constants? no.

Need maybe update `AuthContext Profile` maybe no.

Need maybe create `src/pages/Documentos.tsx`. Need maybe import `FileText, Download, Eye, Loader2, AlertCircle`. Use `Dialog` etc.
Need `useAuth`.
Need define Doc interface with `colaborador_id: string | null; tipo: string; mes: number; ano: number; storage_path: string; status: string; nome_pdf: string; created_at: string; nome? maybe no`.
Need `monthLabel`.
Need group:
const grouped = docs.reduce<Record<string, Record<string, Doc[]>>>...
Use type key `${tipo}|${ano}-${mes}`.
Need `openPreview(doc)`:
setSelected(doc); setPreviewUrl(""); setPreviewLoading(true);
const { data, error } = await supabase.storage.from("documentos").createSignedUrl(doc.storage_path, 300);
if error toast.error; else setPreviewUrl(data.signedUrl);
Need Dialog open with selected. If `previewUrl`, iframe. Need maybe iframe title.
Need maybe `download` link? Not required.
Need if no docs.

Need admin page:
Potential long >100 lines, but okay maybe 300. Could create subcomponents? Better create small components? But one file maybe >100. Guidelines aim <100. Could create `src/pages/admin/Documentos.tsx` with helper functions and components. Might be >100. Fine.

Need maybe use shadcn `Select` and `Input`, `Label`, `Button`, `Badge`, `Dialog`, `Textarea`, `Card`, `Progress`, maybe. Use existing components.

Need maybe no custom CSS.

Need maybe implement "Painel mostrando status do processamento: vinculados com sucesso, vinculados manualmente, pendentes".
State `stats`:
const [stats,setStats] = useState({auto:0, manual:0, pending:0, total:0});
After upload set based on results. Also maybe load existing docs counts:
loadExisting = supabase.from("documentos").select("status, colaborador_id").limit(1000)
stats.total = data.length; stats.pending = data.filter(...).length; stats.vinculados = data.filter(status==='vinculado').length; stats.manuais = 0 (unknown)
But "painel processamento" maybe current upload. We'll show "Último processamento" plus "Banco atual" counts.
Need maybe not admin access all via RLS.

Need "Vincular manualmente" dropdown with list of colaboradores cadastrados. Use Select.
Need "Colaborador não cadastrado" button saves pending. Need input name.
Need if no profiles? Show.

Need maybe "Ao subir o PDF, usar PDF.js para extrair texto..." We'll process on file selection and type/month/year. Maybe button "Processar PDF".
Need maybe "Ao subir o PDF" means after selecting file. We can call process when file selected if type/mes/ano present. Also have button.
Need maybe avoid re-processing every file change if incomplete. Use effect:
useEffect(() => {
if (file && tipo && mes && ano) processPdf();
}, [file, tipo, mes, ano]);
But processPdf defined with useCallback? Need import useCallback. Could just not use effect; button. "Ao subir" maybe less. Use `onChange` on file input and call if fields. But function async. Simpler: Button.
Maybe add "Processar PDF" button. But requirement says ao subir. Hmm. We can call on file input change with effect.

Need maybe avoid repeated processing when file object changes. We can use `void` in useEffect.
Potential TS: `HTMLInputElement` value file.

Need maybe handle `file` type File | null.
Need maybe `pageResults` type:
type PageResult = {
pageNumber: number;
text: string;
status: "auto" | "manual" | "pending";
profileId?: string;
profileName?: string;
score?: number;
identifiedName: string;
uploaded?: boolean;
storagePath?: string;
};
Need `manualProfileByPage` state Record<number,string>; `identifiedNames` Record<number,string>.
Need after process set identifiedNames page -> maybe extract first line from page text?
`guessNameFromText(text)`:
const lines = text.split(/\n+/).map(trim).filter(Boolean);
return lines[0]?.slice(0, 80) ?? `Página ${pageNumber}`;
But page text from PDF.js joined with spaces no newlines. Could use regex? Just `text.slice(0,100)`.
Need maybe manualName default "Colaborador não identificado".
Need maybe "salva como pendente com o nome identificado no PDF" Use text input. Good.

Need upload function:
const uploadPagePdf = async (pageResult: PageResult): Promise<{ path:string; profileId: string|null; status: string; nomePdf: string }> => {
const pageBlob = await createSinglePagePdf(file, pageResult.pageNumber);
const ext = pageResult.profileId ? pageResult.profileId : "pendentes";
const path = pageResult.profileId
? getDocumentStoragePath(pageResult.profileId, tipo, ano, mes)
: getPendingDocumentStoragePath(tipo, ano, mes, pageResult.pageNumber);
const { error } = await supabase.storage.from("documentos").upload(path, pageBlob, { contentType: "application/pdf", upsert: true, cacheControl: "3600" });
if (error) throw new Error(`Erro ao salvar PDF: ${error.message}`);
const payload: any = {
colaborador_id: pageResult.profileId,
tipo,
mes: Number(mes),
ano: Number(ano),
storage_path: path,
status: pageResult.profileId ? "vinculado" : "pendente",
nome_pdf: pageResult.identifiedName,
};
const { error: dbError } = await supabase.from("documentos").insert(payload);
if (dbError) throw new Error(`Documento extraído, mas falhou ao registrar: ${dbError.message}`);
return { ... };
}
Need if same path for multiple pages and same employee, upload overwrites. DB rows duplicate. Could maybe `await supabase.from("documentos").delete().eq("colaborador_id", profileId).eq("tipo", tipo).eq("mes", Number(mes)).eq("ano", Number(ano))` before inserting to avoid duplicates. For manual/auto, do that. For pending, no. This means if PDF has multiple pages for same employee, only last page remains. Not ideal. But avoids duplicates. Could maybe if multiple pages same employee, need combine. Hmm.
Maybe we can not delete. But duplicates undesirable. Maybe if same employee multiple pages, only one path. Could overwrite and multiple DB rows. Bad.
Could if same employee, path with page number? But requirement path exact. Maybe not.
Could if same employee, create combined PDF? Too much.
Maybe use page number in `nome_pdf` but path same. Hmm.
Maybe we can save page-level files with path exact and DB `storage_path` same. Duplicates. We can delete previous docs for same employee/type/month/year before insert. Then if same employee has multiple pages, only last page stored. Not good.
Maybe use `pdf-lib` to merge pages per employee. Let's implement better:
- After extracting pages and matching, group pages by target (profileId or pending key).
- For each group, create a multi-page PDF containing all pages in that group. Need `mergePdfPages(file, pageNumbers)` function. Then upload once to path. For pending groups, path `documentos/pendentes/${tipo}/${ano}-${mes}/${safeName}-${page1-page2}.pdf` maybe. But requirement path for found. Good. For found, path exact.
- For each page, if profile matched, group by profileId. If manual, group by profileId. If pending, group by `pendente-${page}` or maybe by identifiedName? Could combine pending pages by identifiedName normalized. But if same unidentified name across pages, group. Simpler group by page.
- `createMergedPdf(file, pageNumbers)` returns Blob. Then upload per group. DB insert per group. For pending, `colaborador_id: null`, `nome_pdf` combined names or page names.
This is robust. Need implement `createMergedPdf`.
- For auto/manual found, if multiple pages same employee, merge them.
- For pending, each pending page maybe separate doc with path `documentos/pendentes/${tipo}/${ano}-${mes}/${page.pageNumber}-${slug(identifiedName)}.pdf`.
Need `slugText`.
- Then no duplicate.
Need update `lib/documentos.ts` with `createMergedPdf(file, pageNumbers)`.
Need maybe if group pageNumbers length > 1, merge. Good.
- Upload group:
const path = profileId ? getDocumentStoragePath(profileId, tipo, ano, mes) : getPendingDocumentStoragePath(tipo, ano, mes, pageNumbers, identifiedName)
Need `getPendingDocumentStoragePath(tipo, ano, mes, pageNumbers, name)`.
Need path with no accents. Use slug.

Need maybe "nome_pdf (nome como apareceu no PDF)" for merged pages. Use first page name or combined. Good.

Need maybe "Vinculados manualmente" count. We can mark `source: "auto" | "manual" | "pending"` in local stats. DB status doesn't record manual. Panel can show "Vinculados manualmente (último processamento)" count. Good.
Need maybe "status processamento" after process. Good.

Need maybe "Admin painel showing status" with cards.
Need maybe "Vincular manualmente" action per page. After manual selection, update page result and maybe immediately upload? We can have "Salvar página" button. Simpler: For unmatched, user chooses manual or pending, then clicks "Salvar pendências". But requirement says two options. We can make buttons "Salvar manual" and "Salvar como pendente" per page.
- For manual: set profileId and identifiedName, status manual, then call savePage.
- For pending: set profileId null and identifiedName, status pending, then savePage.
Need `savePage(pageNumber, mode, profileId?)`.
Maybe easier: After processing, for each unmatched page show select and input. A "Salvar decisões" button loops through all pageResults and uploads groups:
- For status auto: include.
- For status manual: require profileId.
- For status pending: require identifiedName.
But requirement "exibir página com duas opções". We can show buttons. Let's implement "Salvar decisões" that validates. That is simpler.
- Buttons:
- "Vincular manualmente" sets status manual and profileId to selected; disabled if no selected.
- "Colaborador não cadastrado" sets status pending and identifiedName default if empty.
- Save all.
Need maybe after manual selection, show badge "Pronto para salvar".
- Stats updated after save.

Need maybe `pageResults` status initial "auto" or "unmatched". Then after user actions "manual"/"pending".
Need maybe `saveDecisions`:
const ready = pageResults.every(r => r.status !== "unmatched")
if no ready, toast.
for each group by key:
profileId = group.find(r=>r.profileId)?.profileId ?? null
if no profileId => pending
pageNumbers = group.map...
blob = await createMergedPdf(file, pageNumbers)
path = profileId ? getDocumentStoragePath(profileId, tipo, ano, mes) : getPendingDocumentStoragePath(...)
upload, insert
collect counts.
Set stats.
Need if auto group and manual group same profile? Could group all with same profile. Good.
Need `grupoKey = profileId ?? `pendente:${normalizeText(r.identifiedName)}:${r.pageNumber}``.
Need `identifiedName` for auto = profile.nome. For manual = selected profile nome. For pending = input.
Need `profileNameById` map.

Need maybe "nome_pdf" for pending = identifiedName. For found = profile.nome.
Need maybe "status" insert "vinculado" if profileId else "pendente".
Need maybe "created_at" default DB.

Need maybe "Admin accesses all" in table load:
const {data} = await supabase.from("documentos").select("*, profiles!inner(id,nome)").order("created_at",{ascending:false})
But PostgREST inner join syntax with FK? Need foreign key relationship to profiles? If `colaborador_id` references profiles(id), then `profiles!inner(id,nome)` works. If pending null, inner join excludes pending. Better use two queries: docs and profiles.
Need maybe DB has FK. We'll specify SQL. But types relationships? no.
Need load profiles separately.
Need maybe docs with null colab and no profile. Good.
Need display profile name from map.

Need maybe storage signed URL for admin? not needed.
Need maybe delete docs? not requested. Avoid.

Need maybe create SQL. Since no SQL tool, perhaps create `src/lib/documentos-schema.sql`? Hmm. We can maybe include in final "O próximo passo necessário é aplicar o SQL da tabela/bucket; não foi possível executar por falta da ferramenta SQL". But user didn't ask. However final summary must include action required. The instructions say after code changes, if action required include it. Good.

But maybe we can use `dyad-add-dependency` first. Need add pdfjs-dist and pdf-lib. Use one block.
</think><dyad-add-dependency packages="pdfjs-dist pdf-lib"></dyad-add-dependency><dyad-write path="src/lib/documentos.ts" description="Cria módulo de documentos com PDF.js e pdf-lib">
import * as pdfjsLib from "pdfjs-dist";
import { GlobalWorkerOptions } from "pdfjs-dist";
import { PDFDocument } from "pdf-lib";

// Configuração do worker do PDF.js
GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.mjs", import.meta.url).toString();

export type DocumentType = "contracheque" | "folha_ponto";

export interface Documento {
  id: string;
  colaborador_id: string | null;
  tipo: DocumentType;
  mes: number;
  ano: number;
  storage_path: string;
  status: "vinculado" | "pendente";
  nome_pdf: string;
  created_at: string;
}

export interface Profile {
  id: string;
  nome: string;
}

export interface PageResult {
  pageNumber: number;
  text: string;
  status: "auto" | "manual" | "pending";
  profileId?: string;
  profileName?: string;
  score?: number;
  identifiedName: string;
  storagePath?: string;
}

export interface UploadStats {
  auto: number;
  manual: number;
  pending: number;
  total: number;
}

// Funções utilitárias
export function normalizeText(value: string): string {
  return (value ?? "")
    .toLocaleLowerCase("pt-BR")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function formatDocMonth(mes: number, ano: number): string {
  return `${ano}-${String(mes).padStart(2, "0")}`;
}

export function getDocumentStoragePath(colaboradorId: string, tipo: DocumentType, ano: number, mes: number): string {
  return `documentos/${colaboradorId}/${tipo}/${ano}-${String(mes).padStart(2, "0")}.pdf`;
}

export function getPendingDocumentStoragePath(tipo: DocumentType, ano: number, mes: number, pageNumbers: number[], identifiedName: string): string {
  const slug = normalizeText(identifiedName).replace(/\s+/g, "-").slice(0, 50);
  return `documentos/pendentes/${tipo}/${ano}-${String(mes).padStart(2, "0")}/${pageNumbers.join("-")}-${slug}.pdf`;
}

// Similaridade de texto
function levenshteinDistance(a: string, b: string): number {
  if (a.length === 0) return b.length;
  if (b.length === 0) return a.length;
  
  const matrix = Array(b.length + 1).fill(null).map(() => Array(a.length + 1).fill(null));
  
  for (let i = 0; i <= a.length; i++) matrix[0][i] = i;
  for (let j = 0; j <= b.length; j++) matrix[j][0] = j;
  
  for (let j = 1; j <= b.length; j++) {
    for (let i = 1; i <= a.length; i++) {
      const indicator = a[i - 1] === b[j - 1] ? 0 : 1;
      matrix[j][i] = Math.min(
        matrix[j][i - 1] + 1,
        matrix[j - 1][i] + 1,
        matrix[j - 1][i - 1] + indicator
      );
    }
  }
  
  return matrix[b.length][a.length];
}

export function similarity(a: string, b: string): number {
  if (!a || !b) return 0;
  
  // Se um é substring do outro, retorna 1
  if (a.includes(b) || b.includes(a)) return 1;
  
  const max = Math.max(a.length, b.length);
  const distance = levenshteinDistance(a, b);
  return 1 - distance / max;
}

// Extração de texto do PDF
export async function extractPdfText(file: File): Promise<{ pageNumber: number; text: string }[]> {
  const arrayBuffer = await file.arrayBuffer();
  const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
  const pdf = await loadingTask.promise;
  
  const pages: { pageNumber: number; text: string }[] = [];
  
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const textContent = await page.getTextContent();
    const text = textContent.items.map((item: any) => "str" in item ? item.str : "").join(" ");
    pages.push({ pageNumber: i, text });
  }
  
  return pages;
}

// Cria PDF de uma única página
export async function createSinglePagePdf(file: File, pageNumber: number): Promise<Blob> {
  const originalPdf = await PDFDocument.load(await file.arrayBuffer());
  const newPdf = await PDFDocument.create();
  
  const [page] = await newPdf.copyPages(originalPdf, [pageNumber - 1]);
  newPdf.addPage(page);
  
  const bytes = await newPdf.save();
  return new Blob([bytes], { type: "application/pdf" });
}

// Cria PDF mesclado de múltiplas páginas
export async function createMergedPdf(file: File, pageNumbers: number[]): Promise<Blob> {
  const originalPdf = await PDFDocument.load(await file.arrayBuffer());
  const newPdf = await PDFDocument.create();
  
  for (const pageNum of pageNumbers) {
    const [page] = await newPdf.copyPages(originalPdf, [pageNum - 1]);
    newPdf.addPage(page);
  }
  
  const bytes = await newPdf.save();
  return new Blob([bytes], { type: "application/pdf" });
}

// Encontra melhor correspondência de perfil
export function findBestProfileMatch(
  pageText: string,
  profiles: Profile[]
): { profile: Profile; score: number; matchedText: string } | null {

  const page = normalizeText(pageText);

  // ==================================================
  // ETAPA 1 - CPF (100% confiável)
  // ==================================================

  const cpfMatch = page.match(/\d{3}\.?\d{3}\.?\d{3}-?\d{2}/);

  if (cpfMatch) {
    const cpf = cpfMatch[0].replace(/\D/g, "");

    const profile = profiles.find(
      p => p.cpf?.replace(/\D/g, "") === cpf
    );

    if (profile) {
      return {
        profile,
        score: 1,
        matchedText: cpf,
      };
    }
  }

  // ==================================================
  // ETAPA 2 - NOME COMPLETO
  // ==================================================

  let bestMatch: {
    profile: Profile;
    score: number;
    matchedText: string;
  } | null = null;

  for (const profile of profiles) {

    if (!profile.nome) continue;

    const profileName = normalizeText(profile.nome);

    // nome completo encontrado
    if (page.includes(profileName)) {

      return {
        profile,
        score: 0.99,
        matchedText: profile.nome,
      };
    }

    const tokens = profileName
      .split(" ")
      .filter(t => t.length >= 3);

    const matchedTokens = tokens.filter(
      token => page.includes(token)
    );

    const tokenScore =
      matchedTokens.length / tokens.length;

    // Exigir pelo menos 80% dos tokens
    if (tokenScore >= 0.8) {

      const score = tokenScore;

      if (
        !bestMatch ||
        score > bestMatch.score
      ) {
        bestMatch = {
          profile,
          score,
          matchedText: matchedTokens.join(" "),
        };
      }
    }
  }

  return bestMatch;
}

// Gera nome identificado a partir do texto
export function guessNameFromText(text: string): string {
  const lines = text.split(/\n+/).map((line: string) => line.trim()).filter(Boolean);
  const firstLine = lines[0]?.slice(0, 80) || "";
  return firstLine || "Colaborador não identificado";
}