/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrocasRouteImport } from './routes/_authenticated/trocas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTrocasRouteImport } from './routes/_authenticated/admin/trocas'
import { Route as AuthenticatedAdminSolicitacoesRouteImport } from './routes/_authenticated/admin/solicitacoes'
import { Route as AuthenticatedAdminFuncionariosRouteImport } from './routes/_authenticated/admin/funcionarios'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin/calendario'
import { Route as AuthenticatedAdminBloqueiosRouteImport } from './routes/_authenticated/admin/bloqueios'
import { Route as AuthenticatedAdminAprovacoesRouteImport } from './routes/_authenticated/admin/aprovacoes'
import { Route as ApiPublicHooksSorteioFolgasRouteImport } from './routes/api/public/hooks/sorteio-folgas'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrocasRoute = AuthenticatedTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTrocasRoute =
  AuthenticatedAdminTrocasRouteImport.update({
    id: '/trocas',
    path: '/trocas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSolicitacoesRoute =
  AuthenticatedAdminSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFuncionariosRoute =
  AuthenticatedAdminFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBloqueiosRoute =
  AuthenticatedAdminBloqueiosRouteImport.update({
    id: '/bloqueios',
    path: '/bloqueios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAprovacoesRoute =
  AuthenticatedAdminAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksSorteioFolgasRoute =
  ApiPublicHooksSorteioFolgasRouteImport.update({
    id: '/api/public/hooks/sorteio-folgas',
    path: '/api/public/hooks/sorteio-folgas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/trocas': typeof AuthenticatedTrocasRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/trocas': typeof AuthenticatedAdminTrocasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/sorteio-folgas': typeof ApiPublicHooksSorteioFolgasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/trocas': typeof AuthenticatedTrocasRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/trocas': typeof AuthenticatedAdminTrocasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/sorteio-folgas': typeof ApiPublicHooksSorteioFolgasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/trocas': typeof AuthenticatedTrocasRoute
  '/_authenticated/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/_authenticated/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/_authenticated/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/_authenticated/admin/trocas': typeof AuthenticatedAdminTrocasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/sorteio-folgas': typeof ApiPublicHooksSorteioFolgasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/admin'
    | '/calendario'
    | '/historico'
    | '/trocas'
    | '/admin/aprovacoes'
    | '/admin/bloqueios'
    | '/admin/calendario'
    | '/admin/funcionarios'
    | '/admin/solicitacoes'
    | '/admin/trocas'
    | '/admin/'
    | '/api/public/hooks/sorteio-folgas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/calendario'
    | '/historico'
    | '/trocas'
    | '/admin/aprovacoes'
    | '/admin/bloqueios'
    | '/admin/calendario'
    | '/admin/funcionarios'
    | '/admin/solicitacoes'
    | '/admin/trocas'
    | '/admin'
    | '/api/public/hooks/sorteio-folgas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/calendario'
    | '/_authenticated/historico'
    | '/_authenticated/trocas'
    | '/_authenticated/admin/aprovacoes'
    | '/_authenticated/admin/bloqueios'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/funcionarios'
    | '/_authenticated/admin/solicitacoes'
    | '/_authenticated/admin/trocas'
    | '/_authenticated/admin/'
    | '/api/public/hooks/sorteio-folgas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiPublicHooksSorteioFolgasRoute: typeof ApiPublicHooksSorteioFolgasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trocas': {
      id: '/_authenticated/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof AuthenticatedTrocasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trocas': {
      id: '/_authenticated/admin/trocas'
      path: '/trocas'
      fullPath: '/admin/trocas'
      preLoaderRoute: typeof AuthenticatedAdminTrocasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/solicitacoes': {
      id: '/_authenticated/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funcionarios': {
      id: '/_authenticated/admin/funcionarios'
      path: '/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AuthenticatedAdminFuncionariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bloqueios': {
      id: '/_authenticated/admin/bloqueios'
      path: '/bloqueios'
      fullPath: '/admin/bloqueios'
      preLoaderRoute: typeof AuthenticatedAdminBloqueiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aprovacoes': {
      id: '/_authenticated/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminAprovacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/sorteio-folgas': {
      id: '/api/public/hooks/sorteio-folgas'
      path: '/api/public/hooks/sorteio-folgas'
      fullPath: '/api/public/hooks/sorteio-folgas'
      preLoaderRoute: typeof ApiPublicHooksSorteioFolgasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAprovacoesRoute: typeof AuthenticatedAdminAprovacoesRoute
  AuthenticatedAdminBloqueiosRoute: typeof AuthenticatedAdminBloqueiosRoute
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminFuncionariosRoute: typeof AuthenticatedAdminFuncionariosRoute
  AuthenticatedAdminSolicitacoesRoute: typeof AuthenticatedAdminSolicitacoesRoute
  AuthenticatedAdminTrocasRoute: typeof AuthenticatedAdminTrocasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAprovacoesRoute: AuthenticatedAdminAprovacoesRoute,
  AuthenticatedAdminBloqueiosRoute: AuthenticatedAdminBloqueiosRoute,
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminFuncionariosRoute: AuthenticatedAdminFuncionariosRoute,
  AuthenticatedAdminSolicitacoesRoute: AuthenticatedAdminSolicitacoesRoute,
  AuthenticatedAdminTrocasRoute: AuthenticatedAdminTrocasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedTrocasRoute: typeof AuthenticatedTrocasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedTrocasRoute: AuthenticatedTrocasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiPublicHooksSorteioFolgasRoute: ApiPublicHooksSorteioFolgasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
