// ... existing code ...
      <Dialog open={!!resetting} onOpenChange={(o) => !o && (setResetting(null), setNewPwd(""))}>
        <DialogContent>
          <DialogHeader><DialogTitle>Redefinir senha — {resetting?.nome}</DialogTitle></DialogHeader>
          <div className="space-y-2 py-4">
// ... existing code ...